export const course = [
  { title: "Computer Science" },
  { title: "Mechanical" },
  { title: "Electrical" },
  { title: "B.Com" },
  { title: "B.Sc" },
  { title: "Chemistry" },
  { title: "Physics" },
  { title: "Mathematics" },
  { title: "Environmental Science" },
  { title: "Business Administration" },
  { title: "Economics" },
  { title: "Psychology" },
  { title: "History" },
  { title: "English Literature" },
  { title: "Political Science" },
  { title: "Sociology" },
  { title: "Civil Engineering" },
  { title: "Chemical Engineering" },
  { title: "Aerospace Engineering" },
  { title: "Biomedical Engineering" },
  { title: "Nursing" },
  { title: "Medicine" },
  { title: "Dentistry" },
  { title: "Pharmacy" },
  { title: "Law" },
  { title: "Journalism" },
  { title: "Film Studies" },
  { title: "Graphic Design" },
  { title: "Music Theory" },
  { title: "Culinary Arts" },
  { title: "Robotics" },
  { title: "Data Science" },
  { title: "Machine Learning" },
  { title: "Artificial Intelligence" },
  { title: "Cybersecurity" },
  { title: "Digital Marketing" },
  { title: "Environmental Engineering" },
  { title: "Electronics and Communication" },
  { title: "Renewable Energy" },
  { title: "Geology" },
  { title: "Astrophysics" },
  { title: "International Relations" },
  { title: "Ethical Hacking" },
  { title: "Theater Arts" },
  { title: "Fashion Design" },
  { title: "Interior Design" },
  { title: "Hotel Management" },
  { title: "Event Planning" },
  { title: "Sports Management" },
  // Add more course titles as needed
  { title: "Mechatronics Engineering" },
  { title: "Biotechnology" },
  { title: "Astronomy" },
  { title: "Neuroscience" },
  { title: "Marketing Management" },
  { title: "Operations Research" },
  { title: "Business Ethics" },
  { title: "Supply Chain Management" },
  { title: "Computer Engineering" },
  { title: "Materials Science" },
  { title: "Environmental Science" },
  { title: "Criminal Justice" },
  { title: "Graphic Design" },
  { title: "Digital Photography" },
  { title: "Human Resources Management" },
  { title: "Financial Accounting" },
  { title: "Organic Chemistry" },
  { title: "Microbiology" },
  { title: "Political Science" },
  { title: "Comparative Literature" },
  { title: "Public Health" },
  { title: "Social Work" },
  { title: "Urban Planning" },
  { title: "Chemical Engineering" },
  { title: "Mathematical Statistics" },
  { title: "Geography" },
  { title: "Econometrics" },
  { title: "International Business" },
  { title: "Art History" },
  { title: "Philosophy" },
  { title: "Religious Studies" },
  { title: "Criminology" },
  { title: "Environmental Law" },
  { title: "Animation and Visual Effects" },
  { title: "Computer Graphics" },
  { title: "Network Administration" },
  { title: "Human-Computer Interaction" },
  { title: "Digital Media Production" },
  { title: "Biomedical Science" },
  { title: "Forensic Science" },
  { title: "Marine Biology" },
  { title: "Game Design and Development" },
  { title: "Fine Arts" },
  { title: "Drama and Theater" },
  { title: "Fashion Merchandising" },
  { title: "Interior Architecture" },
  { title: "Hospitality Management" },
  { title: "Sports Science" },
  { title: "Physical Therapy" },
  { title: "Public Relations" },
  { title: "Event Management" },
  { title: "Digital Marketing" },
  { title: "Quantum Physics" },
  { title: "Organizational Psychology" },
  { title: "Cybersecurity" },
  { title: "Biomechanical Engineering" },
];

export const AddSkill = [
  { title: "Blockchain" },
  { title: "Ethereum" },
  { title: "Smart Contracts" },
  { title: "Hyperledger Fabric" },
  { title: "Solidity" },
  { title: "Ripple" },
  { title: "Bitcoin" },
  { title: "Cryptocurrency" },
  { title: "Decentralized Finance (DeFi)" },
  { title: "NFTs (Non-Fungible Tokens)" },
  { title: "Machine Learning" },
  { title: "Deep Learning" },
  { title: "Neural Networks" },
  { title: "Natural Language Processing (NLP)" },
  { title: "Computer Vision" },
  { title: "Reinforcement Learning" },
  { title: "GANs (Generative Adversarial Networks)" },
  { title: "Cybersecurity" },
  { title: "Firewalls" },
  { title: "Intrusion Detection System (IDS)" },
  { title: "Encryption" },
  { title: "Penetration Testing" },
  { title: "Incident Response" },
  { title: "Security Information and Event Management (SIEM)" },
  { title: "Vulnerability Assessment" },
  { title: "Zero Trust Security" },
  { title: "Cyber Threat Intelligence" },
  { title: "Identity and Access Management (IAM)" },
  { title: "Blockchain Security" },
  { title: "AI in Cybersecurity" },
  { title: "Quantum Computing" },
  { title: "AI Ethics" },
  { title: "Robotic Process Automation (RPA)" },
  { title: "Data Privacy" },
  { title: "Biometrics" },
  { title: "Cloud Security" },
  { title: "Threat Hunting" },
  { title: "Cryptography" },
  { title: "Digital Forensics" },
  { title: "Secure Coding Practices" },
  { title: "AI in Healthcare" },
  { title: "Blockchain in Supply Chain" },
  { title: "AI in Finance" },
  { title: "Blockchain in Voting Systems" },
  { title: "AI Chatbots" },
  { title: "IoT Security" },
  { title: "Distributed Ledger Technology (DLT)" },
  { title: "AI in Education" },
  { title: "Cybersecurity Frameworks" },
  { title: "React JS" },
  { title: "Node.js" },
  { title: "MongoDB" },
  { title: "Angular" },
  { title: "Python" },
  { title: "Java" },
  { title: "JavaScript" },
  { title: "HTML/CSS" },
  { title: "Vue.js" },
  { title: "AWS" },
  { title: "Docker" },
  { title: "Kubernetes" },
  { title: "SQL" },
  { title: "C#" },
  { title: "Flutter" },
  { title: "Swift" },
  { title: "TensorFlow" },
  { title: "PyTorch" },
  { title: "Ruby on Rails" },
  { title: "PHP" },
  { title: "Bootstrap" },
  { title: "Spring Boot" },
  { title: "Ruby" },
  { title: "TypeScript" },
  { title: "C++" },
  { title: "Go (Golang)" },
  { title: ".NET" },
  { title: "Android" },
  { title: "iOS" },
  { title: "Flutter" },
  { title: "Vue.js" },
  { title: "Express.js" },
  { title: "PostgreSQL" },
  { title: "MySQL" },
  { title: "SQLite" },
  { title: "Firebase" },
  { title: "Redux" },
  { title: "GraphQL" },
  { title: "REST API" },
  { title: "Rust" },
  { title: "SwiftUI" },
  { title: "ASP.NET" },
  { title: "Laravel" },
  { title: "Symfony" },
  { title: "Ruby on Rails" },
  { title: "Flask" },
  { title: "Vue.js" },
  { title: "Nuxt.js" },
  { title: "Ember.js" },
  { title: "Sass" },
  { title: "Less" },
  { title: "Tailwind CSS" },
  { title: "Jest" },
  { title: "Mocha" },
];



export const IndianState =[
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
    "Andaman and Nicobar Islands",
    "Chandigarh",
    "Dadra and Nagar Haveli and Daman and Diu",
    "Lakshadweep",
    "Delhi",
    "Puducherry"
  ]

  
  export const TamilNaduCity =['Pollachi',
  'Cumbum',
  'Vikramasingapuram',
  'Mettur',
  'Udhagamandalam (Ooty)',
  'Vellore',
  'Sivakasi',
  'Periyakulam',
  'Parangipettai',
  'Dindigul',
  'Tiruvannamalai',
  'Sathyamangalam',
  'Padmanabhapuram',
  'Madurai',
  'Namakkal',
  'Kumbakonam',
  'Neyyattinkara',
  'Nagapattinam',
  'Salem',
  'Vadakku Valliyur',
  'Pallikonda',
  'Gudiyatham',
  'Pallapatti',
  'Walajapet',
  'Ramanathapuram',
  'Karur',
  'Arakkonam',
  'Tiruchirappalli',
  'Kanchipuram',
  'Perambalur',
  'Thoothukudi',
  'Tiruttani',
  'Pannaipuram',
  'Chidambaram',
  'Virudhachalam',
  'Ambur',
  'Chennai',
  'Uthamapalayam',
  'Sholingur',
  'Paramakudi',
  'Cuddalore',
  'Uthiramerur',
  'Sirkali',
  'Hosur',
  'Thanjavur',
  'Tirunelveli',
  'Mannargudi',
  'Neyveli',
  'Kovilpatti',
  'Sankarankovil',
  'Aruppukkottai',
  'Puliyur',
  'Karaikudi',
  'Virudhunagar',
  'Tiruvarur',
  'Viluppuram',
  'Rajapalayam',
  'Karaikal',
  'Puliyankudi',
  'Pudukkottai',
  'Vaniyambadi',
  'Avadi',
  'Usilampatti',
  'Nagercoil',
  'Tindivanam',
  'Coimbatore',
  'Palani',
  'Tenkasi',
  'Srivilliputhur',
  'Rasipuram',
  'Palladam',
  'Erode',
  'Pattukkottai',
  'Panagudi',
  'Pudupattinam',
  'Tiruppur',
  'Vedaranyam',]
  
  
  
